name: Build and Deploy
on:
  pull_request: # プルリクエストを作成した場合ビルドが実行されます
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build
      
      - name: Export Next.js application
        run: npm run export
    
      - name: Commit and Push changes
        run: |
         git config --global user.name "soichiro-yamakawa-s"
         git config --global user.email "soichiro.yamakawa.s@quick.jp"
         git add ./out
         git commit -m "Add build and export files"
         git push https://${{ secrets.GH_TOKEN }}@github.com/soichiro-yamakawa-s/build_test.git HEAD:develop        
