name: Build and Deploy
on:
  push:
    branches:
      - main # メインブランチにプッシュされた場合、ビルドが実行されます
env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies dividends
        run: npm install --prefix src/dividends

      - name: Build Next.js dividends
        run: npm run build --prefix src/dividends
      
      - name: Export Next.js dividends
        run: npm run export --prefix src/dividends
      
      - name: Install dependencies supplyChainView
        run: npm install --prefix src/supplyChainView

      - name: Build Next.js supplyChainView
        run: npm run build --prefix src/supplyChainView
      
      - name: Export Next.js supplyChainView
        run: npm run export --prefix src/supplyChainView
        
      - name: Install dependencies corporateDownloader
        run: npm install --prefix src/corporateDownloader

      - name: Build Next.js corporateDownloader
        run: npm run build --prefix src/corporateDownloader
        
      - name: Install dependencies searchReport
        run: npm install --prefix src/searchReport

      - name: Build Next.js searchReport
        run: npm run build --prefix src/searchReport
        
